//
// Created by John on 5/28/2024.
//

#ifndef LOGICGATESANDEVENTS_FOURBITFOURWORDRAM_HPP
#define LOGICGATESANDEVENTS_FOURBITFOURWORDRAM_HPP


class FourBitFourWordRAM {

};


#endif //LOGICGATESANDEVENTS_FOURBITFOURWORDRAM_HPP
